"""Initial migrate

Revision ID: 93dcfc4e4a1e
Revises: 
Create Date: 2024-07-11 15:37:58.335427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93dcfc4e4a1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('organisations',
    sa.Column('orgId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('orgId'),
    sa.UniqueConstraint('orgId')
    )
    op.create_table('organisation_members',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.orgId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('user_id', 'organisation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation_members')
    op.drop_table('organisations')
    op.drop_table('users')
    # ### end Alembic commands ###
